# Test files for bls_data_catalog
python_tests(
    name="tests",
    sources=["test_*.py"],
    resolve="bls_data_catalog_env",
    dependencies=[
        "//bls_data_catalog:reqs",
        "//bls_data_catalog:scripts",
    ],
)
