python_requirements(
    name="requirements",
    source="requirements.txt",
    resolve="semantic_manifest_editor_backend_env",
)

python_sources(
    name="lib",
    resolve="semantic_manifest_editor_backend_env",
    dependencies=[":requirements"],
)
