name: 'bls_data_catalog'
version: '1.0.0'
config-version: 2

profile: 'bls_data_catalog'

model-paths: ["models"]
seed-paths: ["data"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  bls_data_catalog:
    +schema: raw
    +materialized: table

models:
  bls_data_catalog:
    views:
      +materialized: view
      +schema: analytics
